FROM node:latest

RUN apt-get update
#RUN npm install -g npm
RUN npm install npm@latest -g

# Install app dependencies\
VOLUME /mnt/build
WORKDIR /src
COPY package.json /src/package.json
RUN npm update

#Build the app
COPY . /src
RUN npm run build
