- hosts: all
  connection: local
  vars:
    packer_version: 0.10.1
    packer_download_url: "https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip"
    packer_archive_path: "/var/cache/packer/packer_{{ packer_version }}"
    packer_binary_path: "/usr/local/bin"
    packer_plugins: {}
    packer_force_install: False
    human_log_plugin: "human_log.py"  
    callback_dir: "/usr/share/ansible/plugins/callback/"

  tasks:

  - name: check if human_log is downloaded
    stat: path={{ callback_dir }}/{{human_log_plugin}}
    register: callback_plugin

  - name: check if packer is installed
    stat: path=/usr/local/bin/packer
    register: packer_bin

  - name: Install node packages
    become: yes
    apt: name={{item}} state=present
    with_items:
      - nodejs
      - nodejs-dev
      - npm
      - nodejs-legacy

  - name: trust MSFT package key
    apt_key:
      url: "https://packages.microsoft.com/keys/microsoft.asc"
      state: present
    become: yes

  - name: create callback plugins dir
    become: yes
    file:
      path: "{{ callback_dir }}"
      state: directory

  - name: set ansible callback config
    become: yes
    lineinfile:
      path: /etc/ansible/ansible.cfg
      regexp: '^callback_plugins=.+'
      line: "callback_plugins={{ callback_dir }}"

  - name: download human callback plugin
    become: yes
    get_url:
      url: "https://raw.githubusercontent.com/n0ts/ansible-human_log/master/human_log.py"
      dest: "{{ callback_dir }}/{{human_log_plugin}}"
    register: download
    when: not callback_plugin.stat.exists
  

  - name: Add azure apt repo
    apt_repository:
      repo: deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ wheezy main
      state: present
    become: yes
    
  - name: Install az packages
    become: yes
    apt: name={{item}} state=present allow_unauthenticated=yes
    with_items:
      - apt-transport-https
      - azure-cli

  - name: Install ruby packages
    become: yes
    apt: name={{item}} state=present
    with_items:
      - ruby

  - name: install gems
    become: yes
    shell: gem install graphql-client
    