- hosts: all
  connection: local
  vars:
  - ssh_port: 9022
  - ssh_user: "{{ lookup('env','my_user') }}"
  - my_key: "{{ lookup('env','my_key') }}"
  - key_file: "{{ lookup('env','key_file') }}"
  - report_output: "/var/cache/compliance_results/"
  - report_repo: "{{ lookup('env','report_repo') }}"

  tasks:
    - name: get aks-ssh ip
      shell: kubectl get services |grep aks-ssh |awk '{print $4}'
      register: aks_ssh_ip

    - name: Create key dir
      file:
        path: "{{ report_output }}"
        state: directory
           
    - name: Exec build node compliance checks
      become: yes
      shell: "inspec exec {{ item }} --reporter=documentation:{{ report_output }}`echo {{ item }}|tr '/' '_'|tr -d ':' `"
      with_items: 
      -  "https://github.com/dev-sec/linux-baseline"
      ignore_errors: yes
      no_log: true

    - name: exec remote compliance checks
      become: yes
      shell: "inspec exec {{ item }} -t ssh://{{ ssh_user }}@{{ aks_ssh_ip.stdout }} -p {{ ssh_port }} -i {{ key_file }} --reporter=documentation:{{ report_output }}`echo {{ item }}|tr '/' '_'|tr -d ':' `"
      with_items: 
      -  "https://github.com/dev-sec/cis-kubernetes-benchmark"
      -  "https://github.com/dev-sec/cis-docker-benchmark"
      ignore_errors: yes
      no_log: true

    - name: archive compliance reports
      shell: |
        cd ~
        rm -rf ~/Compliance_Reports
        git clone {{ report_repo }}
        cp {{ report_output }}/* ~/Compliance_Reports
        cd ~/Compliance_Reports
        git add .
        git commit -m "Update compliance reports"
        git push


