apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: book-search
  name: cache-db{{fullVersion}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: book-search
        version: {{fullVersion}}     
        service: cache-db
    spec:
      containers:
      - env:
        image: "redislabs/rejson:latest"
        name: rejson
        ports:
        - containerPort: 6379
        imagePullPolicy: Always
      restartPolicy: Always
