apiVersion: v1
kind: Service
metadata:
  labels:
    app: book-search
  name: book-api
spec:
  ports:
  - port: 8222
  selector:
    service: book-api
    version: {{fullVersion}}
  type: LoadBalancer    