apiVersion: v1
kind: Service
metadata:
  labels:
    app: book-search
  name: book-website
spec:
  ports:
  - port: 80
  selector:
    service: book-website
    version: {{fullVersion}}
  type: LoadBalancer